version: "3"

services:
  web:
    build: .

    ports:
      - 8080:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database

  celery:
    build: .
    command: bash -c "celery -A DeliGOODwin worker -l info -B"
    links:
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  redis:
    image: redis
    ports:
      - "6379:6379"